PLT-259:Fixed Placement Block issue in vsphere cluster creation
spectrocloud/terraform-spectrocloud-modules pull request #58
Opened 2023-02-03 11:42 UTC by SivaanandM

2023-02-03 15:13 UTC, nikchern requested changes

2023-02-06 05:45 UTC, SivaanandM commented on spectro-cluster-vsphere.tf
> -      dynamic "placement" {
no fix is needed in Provider,  we need to alter the yaml format.

2023-02-07 06:09 UTC, nikchern requested changes

2023-02-07 06:09 UTC, nikchern commented on examples/vsphere/providers.tf
> +      version = "0.11.0"
```suggestion
      version = ">= 0.11.0"
```

2023-02-07 06:13 UTC, nikchern approved these changes

2023-02-07 06:13 UTC, merged