PLT-866: Added support for credential type secret for OCI registry and backup storage
spectrocloud/terraform-spectrocloud-modules pull request #81
Opened 2023-12-05 07:35 UTC by SivaanandM

2023-12-05 16:35 UTC, nikchern requested changes

2023-12-05 16:35 UTC, nikchern commented on spectro-registry.tf
>      credential_type = each.value.credential_type
```suggestion
    credential_type = try(each.value.credential_type, "sts")
```

2023-12-05 16:44 UTC, SivaanandM commented on spectro-registry.tf
>      credential_type = each.value.credential_type
removed default value

2023-12-06 04:13 UTC, nikchern approved these changes

2023-12-06 04:14 UTC, merged